### ISSUE TITLE
Separation between modules and libraries?

### ISSUE THREAD

**Issue by the-emerald** [suclearnub/scubot#48]
Given that `reactionscroll.py` is not a module, should there be a distinction made beteween modules (that are usable) and helper libraries?

**Comment by hxtk** [comment]
This issue is obviated by treating `reactionscroll.py` as a dependency rather than an integral part of the library, e.g., `pip install git+https://github.com/scubot/reaction-scroll.git`

**Comment by the-emerald** [comment]
Would it be a good idea to just ship it with the bot? It seems to be an often-used library.

**Comment by hxtk** [comment]
That requires a user of the API to have the rest of the bot in order to write a module that uses that API.

Any attempt to import their module for testing would crash unless they had arranged it in a directory structure that matched that of the bot and had a `reactionscroll.py` file, while listing it as a dependency will ensure that it is installed identically in every environment in which the module could be executed.
